### ISSUE TITLE
Logging issues

### ISSUE THREAD

**Issue by Vishnubala95** [dice-group/hawk#23]
Hi,
Can anybody help me with the username and password to access HAWK login

**Comment by RicardoUsbeck** [comment]
Hi, 

what exactly do you mean? Can you provide a URL or a screenshot?

**Comment by RicardoUsbeck** [comment]
Hi, 
the server is running on port 8181 according to https://github.com/dice-group/hawk/blob/master/src/main/resources/application.properties#L1 

Can you please try this out?

**Comment by RicardoUsbeck** [comment]
I also updated https://github.com/dice-group/hawk/blob/master/README.md Please have a look.

**Comment by Vishnubala95** [comment]
Yeah done. Thanks for the help
